export const scheduleTiming = [
  {
    id: 0,
    title: "Sun",
    startTime: null,
    endTime: null,
    addFields: false,
  },
  {
    id: 1,
    title: "Mon",
    startTime: null,
    endTime: null,
    addFields: false,
  },
  {
    id: 2,
    title: "Tue",
    startTime: null,
    endTime: null,
    addFields: false,
  },
  {
    id: 3,
    title: "Wed",
    startTime: null,
    endTime: null,
    addFields: false,
  },
  {
    id: 4,
    title: "Thu",
    startTime: null,
    endTime: null,
    addFields: false,
  },
  {
    id: 5,
    title: "Fri",
    startTime: null,
    endTime: null,
    addFields: false,
  },
  {
    id: 6,
    title: "Sat",
    startTime: null,
    endTime: null,
    addFields: false,
  },
];
