export const DoctorsListingMock = [
  {
    columnName: "Therapist",
    name: "Dr. Jasica",
    status: "Online",
    rating: 4.4,
    fee: "$ 50.00",
    action: "",
  },
  {
    columnName: "Status",
    name: "Dr. Jasica",
    status: "Online",
    rating: 4.4,
    fee: "$ 50.00",
    action: "",
  },
  {
    columnName: "Rate",
    name: "Dr. Jasica",
    status: "Online",
    rating: 4.4,
    fee: "$ 50.00",
    action: "",
  },
  {
    columnName: "Fee",
    name: "Dr. Jasica",
    status: "Online",
    rating: 4.4,
    fee: "$ 50.00",
    action: "",
  },
  {
    columnName: "",
    name: "Dr. Jasica",
    status: "Online",
    rating: 4.4,
    fee: "$ 50.00",
    action: "",
  },
];
